### PR TITLE
Pydanticv2 in modernpython

### PR DESCRIPTION
**Pull request by guillaume-alliander**
Upgrade pydantic to V2 in modernpython.

This does not change anything in the functionality.

### CODE REVIEW

**Comment by Haifischbecken** [comment]
Hey @guillaume-alliander, this branch looks ready for merge, other than the fact that there is one sign-off missing. If you agree please sign-off the last commit and set the PR to ready.

To retroactively sign-off on the commit you likely have to create a new branch and PR from that branch.
To save you the hassle of looking up hashes and syntax here are the commands:

```bash
git checkout 1575743ffed41e5018de8b1986da78963a358f2c -b fix-sign-off
git cherry-pick -s 0e2cd2c1f51b9639eed0b0d924d0375f8622ca01
```
Then you can push the `fix-sign-off` branch and create a new PR.

Thanks for your work, I was about to do it myself when I saw you already did everything I was looking for.

**Comment by guillaume-alliander** [comment]
That was quick :)

**Comment by Haifischbecken** [comment]
@guillaume-alliander This is not interfering with anything that already exists as far as I can tell and I think the sooner this is available the better. I was wondering however; is there a reason other than personal taste for opting to use pydantic.dataclasses instead of pydantic.basemodel?

**Comment by guillaume-alliander** [comment]
It is not even a question of taste :) 

I started with python `dataclass`, moved to pydantic and tried to keep it as-is. I do think now that `BaseModel` would be better (more supported, developed), and I do not think it would have an impact, so it is something which is on my todo list.

**Comment by Haifischbecken** [comment]
Great to hear, I am currently refactoring cimpy to work with the newly generated classes. There will be some smaller changes coming in a patch and I intend to rename the language pack to `python_pydantic_dataclass` to be more descriptive.
I had one more question. You are putting some annotations in `json_schema_extra`, are you actually using them in a json schema or was that just a convenient way to store them? I am asking because that field is limited to JSON legal formats and I like the change from list to set for possible_profiles which seems to be impossible in `json_schema_extra`.

**Comment by guillaume-alliander** [comment]
The thing is that in pydantic v2, `json_schema_extra` is the only way to store metadata next to their field, I think. And you are correct that it is limited to json. 

This is actually used in cimpy, to know which field to export in which profile. 

The way this is built, is that all resources are bundled across all profiles, with metadata per field to know to which profile(s) it actually belongs. That way, we do not need to have (for instance) `pycgmes.EQ.Powertransformer` (_without_ field `beforeShortCircuitAnglePf`) and `pycgmes.SC.Powertransformer` (_with_ field `beforeShortCircuitAnglePf`). We have only one `pycgmes.Powertransformer` with metadata. 

It seems like a nice way to do it (for which I cannot take the merit, it comes from `cimgen` itself), which is deeply built-in, changing that would be tricky, and it is indeed used in `cimpy`, for the export.

**Comment by guillaume-alliander** [comment]
> Is there a nicer way to access them than `obj.__dataclass_fields[attr_name].default.json_schema_extra["in_profiles"]`? 

If `attr_name` is dynamic, I think that `getattr(obj, attr_name)` should be fine and is a tad more pythonic than `obj.__dataclass_fields[attr_name]`, but the rest is needed. 

You got me thinking about breaking changes. 

Currently, fields are just that, pydantic fields:

```python
# In BaseVoltage
    nominalVoltage: float = Field(
        default=0.0,
        json_schema_extra={
            "in_profiles": [
                Profile.EQBD,
                Profile.EQ,
            ]
        },
    )
```
I guess we could have all fields being CgmesAttributeType, for instance:
```python
# Somewhere generic.py
class CgmesAttributeType[T](BaseModel):
    value: T
    in_profiles: set[str]


# In BaseVoltage.py
   nominalVoltage: CgmesAttribute[float]= CgmesAttribute(value=0.0, in_profiles={
                Profile.EQBD,
                Profile.EQ,
            }
   )
```

Then everywhere we would use that, it would be `getattr(resource, 'nominalVoltage').in_profiles`. Might be really nice, but would be a breaking change as well.

To have this working, we would need to add a Before Annotated Validator, which could do the conversion itself, add the profile based on the metadata and actually make the change non-breaking when creating resources. 

Using the metadata would still be a breaking change.

**Comment by Haifischbecken** [comment]
`getattr()` directly retruns the value not the field object so it can be used like every normal class. If a default value is specified it even does this on the class (which seems wierd to me but I tested it).
I somewhat dislike the idea of adding an extra class for attributes since we then make the usage of the classes less convenient, even if only slightly so. I think adding a method like:

```python 
def get_attr_profiles(self, attr_name: str) -> Set[Profile]:
    return {Profile[s] for s in self.__dataclass_fields__[attr_name].default.json_schema_extra["in_profiles"] }
```
to the base class and achieve the same thing getting `base_voltage.get_attr_profiles("nominalVoltage")` instead of `base_voltage.nominalVoltage.in_profile`. The only thing bothering me about this, is not getting an autocomplete on the attribute names.

**Pull request merged**
