### PR TITLE
Moderpython simplification + Attribute NS

### PR DESCRIPTION
**Pull request by guillaume-alliander**
Mostly split `Base.py` in a bunch of smaller, more specific classes, and add attributes NS.

### CODE REVIEW

**Comment by m-mirz** [comment]
@guillaume-alliander What is the state of this PR? Can it be merged before #20 or is there some dependency? Please assign this to me when you would like one of us to have a look.

If you would like to discuss the roadmap or maintainer role with us, feel free to reach out to @dinkelbachjan and me via mail or slack.

**Comment by guillaume-alliander** [comment]
I would like to have confirmation from @chicco785 but this one should be merged before #20 I believe.

**Comment by chicco785** [comment]
> I would like to have confirmation from @chicco785 but this one should be merged before #20 I believe.

yes, i will rebase my changes on top of this PR

**Review by chicco785 — APPROVED** [review]
I had a quick look, it seems fine to me.

**Review by m-mirz — APPROVED** [review]

**Pull request merged**
